const CREATE_NOTE = "CREATE_NOTE";
const UPDATE_NOTE = "UPDATE_NOTE";
const DELETE_NOTE = "DELETE_NOTE";
const GET_NOTES = "GET_NOTES";
const GET_NOTE = "GET_NOTE";

export {
  CREATE_NOTE,
  UPDATE_NOTE,
  DELETE_NOTE,
  GET_NOTES,
  GET_NOTE,
};
